### ISSUE TITLE
Issue with Assignments

### ISSUE THREAD

**Issue by gmccauley** [matbe/MEMDocumentAndExporter#4]
When listing assignments, if "All Users" is used, all groups are returned.

It would be nice if you could split up Required vs Available vs Uninstall assignments.  We use all three and it appears that the groups from all three are combined and displayed.

**Comment by matbe** [comment]
Can you give me an example on the "Required vs Available vs Uninstall assignments" and I will try and recreate it and see if it can be fixed?

**Comment by gmccauley** [comment]
I've attached a screenshot of one of our assignments page (Hopefully, it works).

Basically, if you are a member of the group, you get the app installed because it's required.  Then All Users (except the original group) gets the app uninstalled.

This is the only way that we could force an install if you are added to an Application group, and then force an un-install if you are removed from the group.

![2020-02-17_16-16-50](https://user-images.githubusercontent.com/11580087/74689497-fe393280-51a0-11ea-868e-2aa332034b5b.png)

Not all of our applications are this way.  Most just have "All Users" as the Required or Available Assignment.  When All Users is used, it looks like the script adds all the groups to the word doc instead of just "All Users".

**Comment by matbe** [comment]
Thanks! I will try and recreate and see if it can be presented in a better way.

**Comment by matbe** [comment]
I have pushed a new version (v1.01) please test and see if it fixes the issue with all users and if the assignments are looking better now. I also made a change to Applecertificate and VPPtokens so please check if those work better now.

**Comment by gmccauley** [comment]
Assignments are better!  They now display "All Users" instead of each group, and they are broken up in the document by Required, Available, and Uninstall as requested.  Thanks for that, this is going to be a life saver.

Still getting the same error with the VPP Tokens.  In the document, all the fields in the table have values except token and tokenActionResults.

I think this issue can be closed as it was specific to the Assignments.  I can continue to help with the VPP if needed via the other issue or a new issue can be opened.

**Comment by matbe** [comment]
Please create a new issue for VPP tokens since that is a diffrent issue I think.
Setting this as fixed in v1.01
